name: PyPI
on:
  release:
    types:
      - published

jobs:
  job:
    name: Build and publish
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: "_token"
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set-up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install build twine
      - name: Build the package
        run: |
          python3 -m build
          python3 -m twine check dist/*
      - name: Publish to PyPI
        run: python3 -m twine upload dist/*
